language: node_js
node_js:
  - "6"
  - "4"
services:
  - mongodb
env:
  - JWT_TOKEN_SECRET="eF0yAEsFzjUePOqeg3ifj_8yXBY32jgvEbwV1ECJ5GOXmu1h5rMlnSHNRkodfgom"
  - DB_HOST_TEST="localhost"
after_script:
  - npm run coverage